"""Pure domain foundations for deterministic travel-planning rules."""

from intelligent_travel_assistant.domain.budget import (
    BudgetAssessment,
    BudgetCostItem,
    BudgetSummaryResult,
    CostCategory,
    summarize_budget,
)
from intelligent_travel_assistant.domain.foundation import (
    Coordinates,
    CoordinateSystem,
    CostConfidence,
    CostEntry,
    DomainInvariantError,
    Location,
    Money,
    PlanDayStructure,
    PlanStructure,
    Provider,
    RouteLeg,
    RouteMode,
    SourceCatalog,
    SourceRecord,
    WeatherForecast,
)
from intelligent_travel_assistant.domain.provider_result import (
    DataFreshness,
    ProviderError,
    ProviderErrorCategory,
    ProviderErrorCode,
    ProviderErrorReason,
    ProviderResult,
    ProviderResultStatus,
    evaluate_freshness,
)
from intelligent_travel_assistant.domain.route_validation import (
    DailyRoutePlan,
    ExpectedRouteLeg,
    RouteActivity,
    RouteValidationResult,
    RouteValidationStatus,
)
from intelligent_travel_assistant.domain.schedule import (
    ActivityTimeSlot,
    DailyAvailability,
    TwoDayTimePlan,
)
from intelligent_travel_assistant.domain.trip_request import TripRequestInput

__all__ = [
    "ActivityTimeSlot",
    "BudgetAssessment",
    "BudgetCostItem",
    "BudgetSummaryResult",
    "CoordinateSystem",
    "Coordinates",
    "CostConfidence",
    "CostCategory",
    "CostEntry",
    "DailyAvailability",
    "DailyRoutePlan",
    "DataFreshness",
    "DomainInvariantError",
    "ExpectedRouteLeg",
    "Location",
    "Money",
    "PlanDayStructure",
    "PlanStructure",
    "Provider",
    "ProviderError",
    "ProviderErrorCategory",
    "ProviderErrorCode",
    "ProviderErrorReason",
    "ProviderResult",
    "ProviderResultStatus",
    "RouteLeg",
    "RouteMode",
    "RouteActivity",
    "RouteValidationResult",
    "RouteValidationStatus",
    "SourceCatalog",
    "SourceRecord",
    "TripRequestInput",
    "TwoDayTimePlan",
    "WeatherForecast",
    "evaluate_freshness",
    "summarize_budget",
]
